### ISSUE TITLE
Problem with prompts in the chat

### ISSUE THREAD

**Issue by SomaSharathSurya** [Microsoft/BotBuilder-Location#62] opened 2017-01-23 11:31 UTC
![capture](https://cloud.githubusercontent.com/assets/25243569/22202236/40382b46-e18d-11e6-8d8b-854443841f10.PNG)

I am getting "botbuilder-location:SingleResultFound" prompts in the chat instead of actual message. Please help me to fix this issue asap.

Thanx in advance

**Comment by kgrashad** [comment] 2017-01-23 11:35
Hi @SomaSharathSurya,

This was caused by a breaking change in botbuilder sdk. We already checked in a fix but waiting to get it in npm.

One way to unblock yourself is to force botbuilder to a version before the breaking change. In package.json change botbuilder version to:
"botbuilder": "3.4.4",

**Comment by SomaSharathSurya** [comment] 2017-01-23 12:36
Hi @kgrashad 

Ive tried changing botbuilder version to 3.4.4 the bot is still showing the same prompt. Please help.

**Comment by kgrashad** [comment] 2017-01-23 12:44
Hmmm. Can you try cloning this repo and requiring it from local file system until v1.0.3 makes it to npm?

**Comment by kgrashad** [comment] 2017-01-23 12:47
http://browsenpm.org/help#cloningamodulefromGithub

**Comment by SomaSharathSurya** [comment] 2017-01-23 13:06
Hey @kgrashad  Ive tried cloning this repo(and changed the botbuilder version)  and executed it still i have the same problem.  please tell me what to do?

**Comment by kgrashad** [comment] 2017-01-23 19:19
The fix is now published to [npm](https://www.npmjs.com/package/botbuilder-location)

**Closed by kgrashad** 2017-01-23 19:20 UTC
